version: '3.8'

services:
  msgrelay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msgrelay
    privileged: true  # Notwendig für systemd
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro  # Notwendig für systemd
    ports:
      - "65172:65172"  # Wenn der Service einen Port verwenden soll